# Default, Defaults
markdown: kramdown
#redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: M A T H E U X
email: gauss27@ciencias.unam.mx
description: A small and simple site I made to test out Jekyll.

baseurl: "/jblog"
url: "https://shiftshuffle.github.io/jblog"

 # baseurl the subpath of your site, e.g. /blog

# url Where can people find your site?

# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
twitter: test
facebook: galois.fermat
google:

author: Shift Shuffle
authorBio:
